# Generated by Django 6.0.1 on 2026-02-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('player', 'points')},
        ),
    ]
