# Generated by Django 6.0.1 on 2026-02-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_score_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
