# Generated by Django 6.0.1 on 2026-02-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_alter_player_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
    ]
